language: node_js
node_js:
  - v8
script:
  - npm run lint
  - npm run singel
  - npm test -- --coverage
  - npm run build
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: npm run website:build
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: website/dist
    on:
      branch: master
