language: node_js
node_js:
  - v8
script:
  - yarn lint
  - yarn type-check
  - yarn build
  - yarn test --coverage
cache:
  - yarn
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.9.4
  - export PATH=$HOME/.yarn/bin:$PATH
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  - provider: script
    skip_cleanup: true
    script: yarn website:build
    on:
      branch: master
  - provider: pages
    skip_cleanup: true
    github_token: $GITHUB_TOKEN
    local_dir: packages/website/dist
    on:
      branch: master
