language: node_js
node_js:
  - v8
script:
  - npm run lint
  - npm run singel
  - npm test -- --coverage
  - npm run build
cache:
  - yarn
after_success:
  - bash <(curl -s https://codecov.io/bash)
deploy:
  provider: script
  script: npm run website:deploy
  skip_cleanup: true
  on:
    branch: master
