[build]
  command = "yarn build:fast && yarn website:build && yarn storybook:build"
  publish = "packages/website/public"

[build.environment]
  RUBY_VERSION = "2.6.2"
  YARN_VERSION = "1.19.1"

[[redirects]]
  from = "https://reakit.netlify.com/*"
  to = "https://reakit.io/:splat"
  status = 301
  force = true

[[headers]]
  for = "/storybook/iframe.html"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
