name: install-node-modules
description: Install node modules

inputs:
  cache-pnpm:
    description: Cache pnpm
    default: "false"

runs:
  using: "composite"
  steps:
    - name: Set up Node
      uses: actions/setup-node@v6
      with:
        node-version-file: .nvmrc

    - name: Set up pnpm
      uses: pnpm/action-setup@v4
      with:
        run_install: false

    - name: Get pnpm store directory
      shell: bash
      run: echo "PNPM_STORE_PATH=$(pnpm store path --silent)" >> "$GITHUB_ENV"

    - name: Cache pnpm
      if: inputs.cache-pnpm == 'true'
      uses: actions/cache@v5
      with:
        key: pnpm-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', '.nvmrc') }}
        restore-keys: pnpm-${{ runner.os }}-
        path: ${{ env.PNPM_STORE_PATH }}

    - name: Cache node_modules
      uses: actions/cache@v5
      id: cache-node-modules
      with:
        key: node-modules-${{ runner.os }}-${{ hashFiles('pnpm-lock.yaml', '.nvmrc') }}
        restore-keys: node-modules-${{ runner.os }}-
        path: |
          node_modules
          nextjs/node_modules
          website/node_modules
          site/node_modules
          packages/*/node_modules

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile
