name: plus

on:
  push:
    branches: [main, next]
  pull_request:

permissions:
  contents: read

env:
  NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY }}
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: ${{ secrets.NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY }}
  STRIPE_SECRET_KEY: ${{ secrets.STRIPE_SECRET_KEY }}
  CLERK_SECRET_KEY: ${{ secrets.CLERK_SECRET_KEY }}

jobs:
  test:
    name: Test Plus
    runs-on: ubuntu-latest
    if: github.repository == 'ariakit/ariakit'

    steps:
      - name: Checkout repository
        uses: actions/checkout@v6

      - name: Install node modules
        uses: ./.github/workflows/install-node-modules
        with:
          cache-npm: true

      - name: Install playwright
        uses: ./.github/workflows/install-playwright
        with:
          engine: chromium

      - name: Cache Next.js
        uses: actions/cache@v5
        with:
          path: website/.next
          key: nextjs-${{ github.run_id }}
          restore-keys: nextjs-

      - name: Build website
        run: npm run build-website-lite

      - name: Test
        id: test
        run: xvfb-run npm run test-plus-headed

      - name: Upload test results to GitHub
        if: failure() && steps.test.outcome == 'failure'
        uses: actions/upload-artifact@v6
        with:
          name: plus-test-results
          path: test-results
          retention-days: 30
